## site.title  (note: use same text as heading 1 to avoid duplicate heading in default primer theme)

title: "sport.db - open sports database (e.g. football.db, formula1.db etc.) command line tool and libraries"



